# Generated by Django 5.2 on 2025-10-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidCountyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'us_counties_data',
            },
        ),
        migrations.CreateModel(
            name='CovidStateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('fips', models.IntegerField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'us_states_data',
            },
        ),
        migrations.CreateModel(
            name='CovidUSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
            ],
            options={
                'db_table': 'us_covid_data',
            },
        ),
        migrations.CreateModel(
            name='CDCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('deaths_total', models.IntegerField(default=0)),
                ('data_as_of', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('state', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WHOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(db_index=True)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('who_region', models.CharField(blank=True, max_length=10)),
                ('new_cases', models.IntegerField(default=0)),
                ('cumulative_cases', models.IntegerField(default=0)),
                ('new_deaths', models.IntegerField(default=0)),
                ('cumulative_deaths', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'WHO COVID Data',
                'verbose_name_plural': 'WHO COVID Data',
                'ordering': ['-date_reported', 'country'],
                'unique_together': {('date_reported', 'country_code')},
            },
        ),
    ]
