# Generated by Django 5.1.3 on 2025-01-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='covidcountydata',
            table='us_counties_data',
        ),
        migrations.AlterModelTable(
            name='covidstatedata',
            table='us_states_data',
        ),
        migrations.AlterModelTable(
            name='covidusdata',
            table='us_covid_data',
        ),
    ]
