# Generated by Django 5.2 on 2025-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdcdata',
            name='weekly_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
