# Generated by Django 5.1.3 on 2025-01-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0002_alter_covidcountydata_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidcountydata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='covidstatedata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='covidusdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='covidcountydata',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='covidstatedata',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='covidusdata',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
