# Generated by Django 5.1.3 on 2025-03-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0003_remove_covidcountydata_id_remove_covidstatedata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=20)),
                ('deaths_new', models.IntegerField(default=0)),
                ('deaths_total', models.IntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('state', 'date')},
            },
        ),
    ]
