# Generated by Django 5.1.3 on 2025-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0004_cdcdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdcdata',
            name='data_as_of',
            field=models.CharField(default='2025-04-15', max_length=20),
            preserve_default=False,
        ),
    ]
