# Generated by Django 5.1.3 on 2025-04-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0005_cdcdata_data_as_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdcdata',
            name='deaths_new',
        ),
        migrations.RemoveField(
            model_name='cdcdata',
            name='fetched_at',
        ),
    ]
