# Generated by Django 5.1.3 on 2025-04-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0006_remove_cdcdata_deaths_new_remove_cdcdata_fetched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcdata',
            name='data_as_of',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cdcdata',
            name='date',
            field=models.DateField(),
        ),
    ]
