# Generated by Django 5.1.3 on 2025-04-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0007_alter_cdcdata_data_as_of_alter_cdcdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdcdata',
            name='data_as_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
