# Generated by Django 5.1.3 on 2025-04-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0008_alter_cdcdata_data_as_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='WHOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reported', models.DateField(db_index=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('who_region', models.CharField(blank=True, max_length=10)),
                ('new_cases', models.IntegerField(default=0)),
                ('cumulative_cases', models.IntegerField(default=0)),
                ('new_deaths', models.IntegerField(default=0)),
                ('cumulative_deaths', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'WHO COVID Data',
                'verbose_name_plural': 'WHO COVID Data',
                'ordering': ['-date_reported', 'country'],
                'unique_together': {('date_reported', 'country_code')},
            },
        ),
    ]
