# Generated by Django 5.2 on 2025-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handler', '0009_whodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidcountydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='covidcountydata',
            name='date',
            field=models.DateField(),
        ),
    ]
